# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNFirebaseSimpleProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseSimpleProject
  pod 'Firebase/Core'

  # target 'RNFirebaseSimpleProject-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'RNFirebaseSimpleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNFirebaseSimpleProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseSimpleProject-tvOS

  target 'RNFirebaseSimpleProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
